"""ADS-B decoder and REST API using pyModeS."""

try:
    # Generated by hatch-vcs at build time (see [tool.hatch.build.hooks.vcs]).
    from adsb._version import __version__
except ImportError:
    # Editable install or working tree without a build: ask the package metadata,
    # falling back to a dev placeholder if the package itself isn't installed.
    try:
        from importlib.metadata import PackageNotFoundError, version

        __version__ = version("adsb-map")
    except (ImportError, PackageNotFoundError):
        __version__ = "0.0.0+unknown"
